pluginDev:
  image: xolocalvendors/hapi-marketplace-api-graphql
  command: -t
  volumes:
    - ../src:/opt/app/current/src
    - ../test:/opt/app/current/test
    - ../coverage:/opt/app/current/coverage
  environment:
    - NODE_ENV=${NODE_ENV}
  links:
    - pgbox
    - esbox

pluginDebug:
  image: xolocalvendors/hapi-marketplace-api-graphql
  command: -dt
  ports:
    - "5858:5858"
  volumes:
    - ../src:/opt/app/current/src
    - ../test:/opt/app/current/test
  links:
    - pgbox
    - esbox
pluginJenkins:
  image: xolocalvendors/hapi-marketplace-api-graphql
  command: -j
  links:
    - pgbox
    - esbox
  environment:
    - LOCAL_REGISTRY_KEY=${LOCAL_REGISTRY_KEY}
pgbox:
  image: xolocalvendors/pgbox:latest
  environment:
    - LANG=en_US.UTF-8
    - POSTGRES_PASSWORD=password
  ports:
    - "5432:5432"
esbox:
  image: xolocalvendors/esbox:5.1.1
  ports:
    - "9200:9200"



